### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by keyplay** [rohban-lab/Salehi_submitted_2020#2]
Hi, may I know the tensorflow version. When I run the python train.py, the following error raised.

Traceback (most recent call last):
  File "train.py", line 141, in <module>
    pgd_steps)
  File "train.py", line 29, in craft_adversarial_samples
    [model.get_layer('latent').get_output_at(0)])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 3936, in function
    model = models.Model(inputs=inputs, outputs=outputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 242, in __new__
    return functional.Functional(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 115, in __init__
    self._init_graph_network(inputs, outputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 191, in _init_graph_network
    self.inputs, self.outputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 931, in _map_graph_network
    str(layers_with_complete_input))
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_1:0", shape=(None, 6144), dtype=float32) at layer "lambda". The following previous layers were accessed without issue: []

**Comment by Atrin78** [comment]
Hi, thanks for your interest in our paper. Please use tensorflow 1.15.0, tensorflow-gpu 1.15.0, and keras 2.3.1. We will update the requirements file.
